name: CI workflow
on:
  push:
    branches:
      [main]
  pull_request:
    branches:
      [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    strategy:
      fail-fast: false
      matrix:
        max-cores: [ 1, 2, 4 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          virtualenv-type: venv

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install flake8
        run: pip install flake8

      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app'
        env:
          CPU_COUNT: ${{ matrix.max-cores }}

      - name: Security Scan with Bandit
        run: |
          pip install bandit
          bandit -r src -ll

      - name: Type Check with mypy
        run: |
          pip install mypy
          mypy src
    
      
